export const data = [
  {
    id: 1,
    avatar: "https://robohash.org/etautsint.png?size=50x50&set=set1",
    name: "Kain",
    username: "kumbers0",
    status: false,
    role: "Senior Quality Engineer",
    email: "klangfitt0@ed.gov",
    teams: "Estimator",
  },
  {
    id: 2,
    avatar:
      "https://robohash.org/quisvelitreprehenderit.png?size=50x50&set=set1",
    name: "Austin",
    username: "aadamoli1",
    status: false,
    role: "Biostatistician IV",
    email: "acastelain1@ucoz.ru",
    teams: "Construction Expeditor",
  },
  {
    id: 3,
    avatar: "https://robohash.org/velmaximeexpedita.png?size=50x50&set=set1",
    name: "Mallory",
    username: "mdatte2",
    status: false,
    role: "Senior Developer",
    email: "muc2@goodreads.com",
    teams: "Construction Expeditor",
  },
  {
    id: 4,
    avatar: "https://robohash.org/dolorquibusdamharum.png?size=50x50&set=set1",
    name: "Heinrick",
    username: "hshankland3",
    status: false,
    role: "Payment Adjustment Coordinator",
    email: "hplewman3@buzzfeed.com",
    teams: "Architect",
  },
  {
    id: 5,
    avatar:
      "https://robohash.org/distinctioerrordolorum.png?size=50x50&set=set1",
    name: "Robinia",
    username: "rchevers4",
    status: true,
    role: "Senior Developer",
    email: "rmeasey4@sakura.ne.jp",
    teams: "Subcontractor",
  },
  {
    id: 6,
    avatar:
      "https://robohash.org/quaeratteneturfacilis.png?size=50x50&set=set1",
    name: "Katheryn",
    username: "kquemby5",
    status: false,
    role: "Nurse",
    email: "khawick5@google.pl",
    teams: "Construction Expeditor",
  },
  {
    id: 7,
    avatar: "https://robohash.org/namnumquamea.png?size=50x50&set=set1",
    name: "Sheffy",
    username: "sgoldbourn6",
    status: false,
    role: "Registered Nurse",
    email: "sbullas6@pbs.org",
    teams: "Electrician",
  },
  {
    id: 8,
    avatar:
      "https://robohash.org/nihilreiciendisvoluptas.png?size=50x50&set=set1",
    name: "Verene",
    username: "vbarradell7",
    status: false,
    role: "Information Systems Manager",
    email: "vhartopp7@dyndns.org",
    teams: "Architect",
  },
  {
    id: 9,
    avatar: "https://robohash.org/facilisnisiqui.png?size=50x50&set=set1",
    name: "Karoly",
    username: "kivan8",
    status: true,
    role: "Quality Control Specialist",
    email: "keymer8@netlog.com",
    teams: "Project Manager",
  },
  {
    id: 10,
    avatar: "https://robohash.org/vitaeutiure.png?size=50x50&set=set1",
    name: "Monroe",
    username: "mingon9",
    status: false,
    role: "Professor",
    email: "mwhitwell9@prnewswire.com",
    teams: "Architect",
  },
  {
    id: 11,
    avatar: "https://robohash.org/quisutquas.png?size=50x50&set=set1",
    name: "Saidee",
    username: "sdacrea",
    status: false,
    role: "Accountant IV",
    email: "sismeada@so-net.ne.jp",
    teams: "Architect",
  },
  {
    id: 12,
    avatar: "https://robohash.org/animietest.png?size=50x50&set=set1",
    name: "Ely",
    username: "ekarlikb",
    status: true,
    role: "Senior Developer",
    email: "efearickb@psu.edu",
    teams: "Electrician",
  },
  {
    id: 13,
    avatar: "https://robohash.org/numquamhicmaxime.png?size=50x50&set=set1",
    name: "Freida",
    username: "fvenusc",
    status: false,
    role: "Help Desk Technician",
    email: "ftoppinc@odnoklassniki.ru",
    teams: "Electrician",
  },
  {
    id: 14,
    avatar:
      "https://robohash.org/reprehenderitconsequunturvel.png?size=50x50&set=set1",
    name: "Brantley",
    username: "bgreenleesd",
    status: false,
    role: "Software Consultant",
    email: "bdoucetted@timesonline.co.uk",
    teams: "Architect",
  },
  {
    id: 15,
    avatar:
      "https://robohash.org/ducimusfugarecusandae.png?size=50x50&set=set1",
    name: "Courtney",
    username: "cmcguffoge",
    status: false,
    role: "Database Administrator I",
    email: "credwoode@geocities.jp",
    teams: "Construction Foreman",
  },
  {
    id: 16,
    avatar: "https://robohash.org/quoautdolor.png?size=50x50&set=set1",
    name: "Rooney",
    username: "rugolettif",
    status: false,
    role: "Junior Executive",
    email: "rbonnerf@edublogs.org",
    teams: "Estimator",
  },
  {
    id: 17,
    avatar: "https://robohash.org/oditetvoluptate.png?size=50x50&set=set1",
    name: "Lurleen",
    username: "lwhysallg",
    status: false,
    role: "Business Systems Development Analyst",
    email: "lgisckeng@cpanel.net",
    teams: "Engineer",
  },
  {
    id: 18,
    avatar: "https://robohash.org/odioanimiest.png?size=50x50&set=set1",
    name: "Witty",
    username: "wvooghth",
    status: false,
    role: "Recruiting Manager",
    email: "wphittiplaceh@networkadvertising.org",
    teams: "Construction Worker",
  },
  {
    id: 19,
    avatar: "https://robohash.org/magnamiureautem.png?size=50x50&set=set1",
    name: "Lauri",
    username: "lmusgravei",
    status: true,
    role: "Quality Engineer",
    email: "loageri@irs.gov",
    teams: "Supervisor",
  },
  {
    id: 20,
    avatar: "https://robohash.org/aututlaboriosam.png?size=50x50&set=set1",
    name: "Ettie",
    username: "elongthornej",
    status: true,
    role: "Nurse Practicioner",
    email: "eduleyj@angelfire.com",
    teams: "Project Manager",
  },
];
